import { useState } from 'react'
import { toast } from 'sonner'
import { useCreateSceneVideoMutation } from '@/store/apis/ai/aiVideos.api'

interface StepPromptPreviewProps {
  scriptId: string
  visualPrompt: string
  environmentName?: string
  environmentAtmosphere?: string
  castNames: string[]
  onBack: () => void
  onNext: (videoId: string, mood: string, order: number) => void
  initialOrder?: number
  initialMood?: string
}

const MOODS = ['CYBER-NOIR', 'NEON-RETRO', 'BIO-GLITCH', 'VOID-SILENCE', 'TECHNO-DREAM', 'DUST-WAVE']

export default function StepPromptPreview({
  scriptId,
  visualPrompt,
  environmentName = 'unknown environment',
  environmentAtmosphere = 'cinematic',
  castNames = [],
  onBack,
  onNext,
  initialOrder = 1,
  initialMood = 'CYBER-NOIR',
}: StepPromptPreviewProps) {
  const [createSceneVideo, { isLoading: isCreatingVideo }] = useCreateSceneVideoMutation()

  const [order, setOrder] = useState<number>(initialOrder)
  const [selectedMood, setSelectedMood] = useState<string>(initialMood)

  const handleGenerateVideo = async () => {
    try {
      const response = await createSceneVideo({
        scriptId: scriptId,
      }).unwrap()

      if (response?.data) {
        toast.success('Video Pipeline Triggered', {
          description: 'Neural render engine accepted script parameters. Generating video frame buffer...',
        })
        onNext(response.data.id, selectedMood, order)
      }
    } catch (err: any) {
      toast.error('Video Generation Failed', {
        description: err.data?.message || 'Error occurred while scheduling render task.',
      })
    }
  }

  return (
    <div className="grid grid-cols-12 gap-8 animate-fade-in">
      {/* Main Prompt/Mood Setup Panel */}
      <div className="col-span-12 lg:col-span-8 flex flex-col gap-6">
        {/* Visual Prompt Section */}
        <section className="glass-panel ghost-border rounded-lg p-8 relative overflow-hidden">
          <div className="absolute top-0 left-0 h-full light-beam opacity-30 pointer-events-none" />
          <div className="flex items-center gap-3 mb-6">
            <span className="material-symbols-outlined text-primary animate-pulse" style={{ fontVariationSettings: "'FILL' 1" }}>auto_awesome</span>
            <h2 className="font-headline text-xl font-bold uppercase tracking-widest text-white">AI Master Visual Prompt</h2>
          </div>
          <p className="text-white/60 mb-4 text-sm leading-relaxed">
            This read-only cinematic prompt was generated by the backend AI engine from your script, cast roster, environment details, and dialogue cues.
          </p>
          <div className="bg-surface-container-lowest/50 p-6 rounded-md ghost-border">
            <div className="w-full bg-transparent font-mono text-sm leading-relaxed text-secondary/90 whitespace-pre-wrap">
              {visualPrompt}
            </div>
          </div>
        </section>

        {/* Mood selection config */}
        <section className="glass-panel ghost-border rounded-lg p-8">
          <div className="flex items-center gap-3 mb-6">
            <span className="material-symbols-outlined text-secondary">palette</span>
            <h2 className="font-headline text-xl font-bold uppercase tracking-widest text-white">Cinematic Color Palette</h2>
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-4">
            {MOODS.map(m => (
              <label
                key={m}
                className={`relative flex items-center justify-between p-4 rounded-lg ghost-border cursor-pointer transition-all ${selectedMood === m
                  ? 'bg-secondary/20 border-secondary text-white shadow-[0_0_15px_rgba(221,183,255,0.15)] font-bold'
                  : 'bg-surface-container-lowest/40 hover:bg-surface-container-low/60 border-white/5 text-white/60'
                  }`}
              >
                <input
                  type="radio"
                  name="mood"
                  value={m}
                  checked={selectedMood === m}
                  onChange={() => setSelectedMood(m)}
                  className="sr-only"
                />
                <span className="font-mono text-xs uppercase tracking-wider">{m}</span>
                {selectedMood === m && (
                  <span className="material-symbols-outlined text-secondary text-sm">radio_button_checked</span>
                )}
              </label>
            ))}
          </div>
        </section>

        {/* Sequence Order */}
        <section className="glass-panel ghost-border rounded-lg p-8">
          <div className="flex items-center gap-3 mb-4">
            <span className="material-symbols-outlined text-accent-cyan">grid_goldenratio</span>
            <h2 className="font-headline text-xl font-bold uppercase tracking-widest text-white">Sequence & Sorting</h2>
          </div>
          <div className="flex items-center gap-4 max-w-xs">
            <label className="text-white/60 text-sm font-mono uppercase tracking-wider flex-shrink-0">Scene Order:</label>
            <input
              type="number"
              value={order}
              onChange={e => setOrder(parseInt(e.target.value) || 1)}
              min={1}
              className="w-24 bg-surface-container-lowest border-none rounded py-2 px-3 text-center ghost-border focus:ring-2 focus:ring-accent-cyan/20 font-mono text-white"
            />
          </div>
        </section>

        {/* Navigation Actions */}
        <div className="flex gap-4">
          <button
            type="button"
            onClick={onBack}
            className="flex-1 py-4 rounded-lg font-bold tracking-widest uppercase text-[10px] text-white/60 hover:text-white hover:bg-white/5 border border-transparent hover:border-white/10 transition-all flex items-center justify-center gap-2"
          >
            <span className="material-symbols-outlined text-sm">arrow_back</span> Back to Script
          </button>
          <button
            type="button"
            onClick={handleGenerateVideo}
            disabled={isCreatingVideo}
            className="flex-[2] py-4 bg-gradient-to-r from-accent-cyan/80 to-secondary rounded-lg font-bold tracking-widest uppercase text-[10px] text-white shadow-lg flex items-center justify-center gap-3 hover:shadow-secondary/30 transition-all border border-white/10 disabled:opacity-70 disabled:cursor-not-allowed"
          >
            {isCreatingVideo ? (
              <>
                <span className="material-symbols-outlined animate-spin text-base">autorenew</span>
                Compiling Neural Assets...
              </>
            ) : (
              <>
                <span className="material-symbols-outlined text-base">rocket_launch</span> Generate Scene Video
              </>
            )}
          </button>
        </div>
      </div>

      {/* Sidebar Summary Info */}
      <div className="col-span-12 lg:col-span-4 flex flex-col gap-6">
        <div className="glass-panel ghost-border rounded-lg p-6 bg-gradient-to-b from-surface-container-low/40 to-surface-container-lowest/30">
          <h3 className="font-headline text-label-md uppercase tracking-widest text-on-surface-variant mb-6 flex items-center gap-2">
            <span className="material-symbols-outlined text-sm">list_alt</span>
            Script Composition
          </h3>

          {/* Selected Environment */}
          <div className="mb-6">
            <p className="text-[10px] text-white/40 uppercase tracking-widest font-mono mb-2">Location Context</p>
            <div className="flex items-center gap-3 bg-surface-container-low/60 p-3 rounded-lg ghost-border">
              <span className="material-symbols-outlined text-accent-cyan text-lg">landscape</span>
              <div>
                <p className="font-bold text-sm text-white">{environmentName}</p>
                <p className="text-[10px] text-secondary uppercase font-mono">{environmentAtmosphere}</p>
              </div>
            </div>
          </div>

          {/* Cast */}
          <div className="mb-6">
            <p className="text-[10px] text-white/40 uppercase tracking-widest font-mono mb-2">Cast Present</p>
            <div className="flex flex-wrap gap-2">
              {castNames.map(name => (
                <div key={name} className="flex items-center gap-2 bg-surface-container-low/60 px-3 py-1.5 rounded-full border border-white/5">
                  <span className="material-symbols-outlined text-[12px] text-white/50">person</span>
                  <span className="text-xs font-medium text-white">{name}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
