import { mainApi } from '../mainApi';
import { ApiResponse } from '@/types/api';
import { ShowChannel } from '@/types/models/core';

export interface ConnectShowToChannelRequest {
  showId: string;
  channelId: string;
}

export interface UpdateShowChannelSettingsRequest {
  isActive: boolean;
  autoPostEpisodes: boolean;
  autoPostScenes: boolean;
  autoGenerateTitles: boolean;
  autoGenerateDescriptions: boolean;
  defaultPublishDelayMinutes?: number;
  preferredPublishTime?: string;
  defaultTitleTemplate?: string;
  defaultDescriptionTemplate?: string;
  tags?: string;
}

export const showChannelsApi = mainApi.injectEndpoints({
  endpoints: (builder) => ({
    getShowChannels: builder.query<ApiResponse<ShowChannel[]>, string>({
      query: (showId) => `/api/show-channels/show/${showId}`,
      providesTags: (result, _err, showId) =>
        result?.data
          ? [
            ...result.data.map(({ id }) => ({ type: 'ShowChannel' as const, id })),
            { type: 'ShowChannel', id: `SHOW_${showId}` },
          ]
          : [{ type: 'ShowChannel', id: `SHOW_${showId}` }],
    }),
    connectShowToChannel: builder.mutation<ApiResponse<boolean>, ConnectShowToChannelRequest>({
      query: (body) => ({ url: '/api/show-channels/connect', method: 'POST', body }),
      invalidatesTags: (_result, _err, { showId }) => [{ type: 'ShowChannel', id: `SHOW_${showId}` }],
    }),
    disconnectShowFromChannel: builder.mutation<ApiResponse<boolean>, ConnectShowToChannelRequest>({
      query: (body) => ({ url: '/api/show-channels/disconnect', method: 'POST', body }),
      invalidatesTags: (_result, _err, { showId }) => [{ type: 'ShowChannel', id: `SHOW_${showId}` }],
    }),
    updateShowChannelSettings: builder.mutation<ApiResponse<boolean>, { showChannelId: string; body: UpdateShowChannelSettingsRequest }>({
      query: ({ showChannelId, body }) => ({ url: `/api/show-channels/${showChannelId}/settings`, method: 'PUT', body }),
      invalidatesTags: (_result, _err, { showChannelId }) => [{ type: 'ShowChannel', id: showChannelId }],
    }),
  }),
});

export const {
  useGetShowChannelsQuery,
  useConnectShowToChannelMutation,
  useDisconnectShowFromChannelMutation,
  useUpdateShowChannelSettingsMutation,
} = showChannelsApi;
