using System.ComponentModel.DataAnnotations.Schema;
using VidiMetrics.Domain.Models.Infra;
using VidiMetrics.Domain.Models.StoryEngine;

namespace VidiMetrics.Domain.Models.Core;

public class ShowChannel : BaseEntity
{
    public Guid ShowId { get; set; }

    [ForeignKey(nameof(ShowId))]
    public Show Show { get; set; } = null!;

    public Guid ChannelId { get; set; }

    [ForeignKey(nameof(ChannelId))]
    public Channel Channel { get; set; } = null!;

    public bool IsActive { get; set; } = true;
    public bool AutoPostEpisodes { get; set; } = false;
    public bool AutoPostScenes { get; set; } = false;
    public bool AutoGenerateTitles { get; set; } = true;
    public bool AutoGenerateDescriptions { get; set; } = true;

    public int? DefaultPublishDelayMinutes { get; set; }
    public TimeSpan? PreferredPublishTime { get; set; }

    public string? DefaultTitleTemplate { get; set; }
    public string? DefaultDescriptionTemplate { get; set; }

    public string? Tags { get; set; }
}