using VidiMetrics.Application.DTOs.Common;

namespace VidiMetrics.Application.DTOs.Core.ShowChannels;

public record ShowChannelResponseDto : BaseResponseDto
{
    public Guid ShowId { get; set; }
    public Guid ChannelId { get; set; }
    public bool IsActive { get; set; }
    public bool AutoPostEpisodes { get; set; }
    public bool AutoPostScenes { get; set; }
    public bool AutoGenerateTitles { get; set; }
    public bool AutoGenerateDescriptions { get; set; }
    public int DefaultPublishDelayMinutes { get; set; }
    public TimeSpan? PreferredPublishTime { get; set; }
    public string? DefaultTitleTemplate { get; set; }
    public string? DefaultDescriptionTemplate { get; set; }
    public string? Tags { get; set; }
}
