using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace VidiMetrics.DataAccess.Migrations
{
    /// <inheritdoc />
    public partial class UpdateChannelsTables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "ContentType",
                table: "ChannelPosts",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<bool>(
                name: "IsAutoGenerated",
                table: "ChannelPosts",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<string>(
                name: "PublishNotes",
                table: "ChannelPosts",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "SourceEntityId",
                table: "ChannelPosts",
                type: "uniqueidentifier",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "SourceEntityType",
                table: "ChannelPosts",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.CreateTable(
                name: "ShowChannels",
                columns: table => new
                {
                    ShowId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    ChannelId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    IsActive = table.Column<bool>(type: "bit", nullable: false),
                    AutoPostEpisodes = table.Column<bool>(type: "bit", nullable: false),
                    AutoPostScenes = table.Column<bool>(type: "bit", nullable: false),
                    AutoGenerateTitles = table.Column<bool>(type: "bit", nullable: false),
                    AutoGenerateDescriptions = table.Column<bool>(type: "bit", nullable: false),
                    DefaultPublishDelayMinutes = table.Column<int>(type: "int", nullable: true),
                    PreferredPublishTime = table.Column<TimeSpan>(type: "time", nullable: true),
                    DefaultTitleTemplate = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DefaultDescriptionTemplate = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Tags = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    CreatedBy = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ShowChannels", x => new { x.ShowId, x.ChannelId });
                    table.ForeignKey(
                        name: "FK_ShowChannels_Channels_ChannelId",
                        column: x => x.ChannelId,
                        principalTable: "Channels",
                        principalColumn: "Id");
                    table.ForeignKey(
                        name: "FK_ShowChannels_Shows_ShowId",
                        column: x => x.ShowId,
                        principalTable: "Shows",
                        principalColumn: "Id");
                });

            migrationBuilder.CreateIndex(
                name: "IX_ShowChannels_ChannelId",
                table: "ShowChannels",
                column: "ChannelId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ShowChannels");

            migrationBuilder.DropColumn(
                name: "ContentType",
                table: "ChannelPosts");

            migrationBuilder.DropColumn(
                name: "IsAutoGenerated",
                table: "ChannelPosts");

            migrationBuilder.DropColumn(
                name: "PublishNotes",
                table: "ChannelPosts");

            migrationBuilder.DropColumn(
                name: "SourceEntityId",
                table: "ChannelPosts");

            migrationBuilder.DropColumn(
                name: "SourceEntityType",
                table: "ChannelPosts");
        }
    }
}
