/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#ddb7ff",
        "on-primary-container": "#deb9ff",
        "surface-container-lowest": "#060e20",
        "tertiary-container": "#a40062",
        "error-container": "#93000a",
        "on-tertiary-container": "#ffb2cf",
        "outline": "#948da2",
        "surface-container-low": "#131b2e",
        "on-error-container": "#ffdad6",
        "secondary-container": "#03b5d3",
        "error": "#ffb4ab",
        "surface-container-highest": "#2d3449",
        "on-secondary-container": "#00424e",
        "secondary-fixed": "#acedff",
        "primary-fixed": "#f0dbff",
        "secondary-fixed-dim": "#4cd7f6",
        "on-error": "#690005",
        "outline-variant": "#494456",
        "surface-container-high": "#222a3d",
        "surface-dim": "#0b1326",
        "primary": "#ddb7ff",
        "on-surface": "#dae2fd",
        "tertiary-fixed-dim": "#ffb0cd",
        "on-secondary": "#003640",
        "on-surface-variant": "#cbc3d9",
        "on-primary-fixed-variant": "#6900b3",
        "primary-container": "#7818c6",
        "surface-bright": "#31394d",
        "inverse-on-surface": "#283044",
        "on-primary": "#490080",
        "tertiary": "#ffb0cd",
        "background": "#0b1326",
        "inverse-primary": "#842bd2",
        "tertiary-fixed": "#ffd9e4",
        "secondary": "#4cd7f6",
        "on-background": "#dae2fd",
        "surface-tint": "#ddb7ff",
        "inverse-surface": "#dae2fd",
        "surface-variant": "#2d3449",
        "on-secondary-fixed-variant": "#004e5c",
        "on-secondary-fixed": "#001f26",
        "on-tertiary-fixed": "#3e0022",
        "surface": "#0b1326",
        "surface-container": "#171f33",
        "on-primary-fixed": "#2c0051",
        "on-tertiary": "#640039",
        "on-tertiary-fixed-variant": "#8c0053"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
